insert into public.dishes (name, servings, description, notes) values
  ('Oats bowl', 2, 'Fast breakfast bowl with oats, yogurt, banana, and peanut butter.', 'Fast breakfast option. Cheap, filling, high-protein, and repeatable.'),
  ('Peanut butter bread with milk', 1, 'Ultra-fast bread, peanut butter, and milk meal.', 'Ultra-fast backup breakfast or snack meal.'),
  ('Chicken curry', 3, 'Nepali-style chicken curry served with rice.', 'Should be Nepali-style rather than overly spicy Indian-style. Keep heat moderate and flavour aromatic.'),
  ('Chicken biryani', 3, 'Pakistani-style aromatic chicken biryani.', 'Preferred style: Pakistani-style biryani. Should be aromatic, rich, and not aggressively spicy.'),
  ('Paneer Mushroom Broccoli Rice', 2, 'Paneer, mushroom, and broccoli rice dish.', 'Flexible rice dish that can lean Indian, Chinese, or fusion depending on spices and sauces.'),
  ('Jeera Aloo', 2, 'Cumin potato dish with onion, garlic, ginger, and coriander.', 'Simple cumin potato dish. Works as a cheap side or light meal with rice, bread, dal, or curry.'),
  ('Malatang-style ramen', 2, 'Flexible soup bowl inspired by malatang and ramen.', 'This is a flexible soup bowl inspired by malatang and ramen, not strict traditional ramen.'),
  ('Tonkotsu ramen', 2, 'Rich pork-bone ramen with noodles and toppings.', 'This is the richer pork-bone ramen option. It should be made less frequently than chicken stock because it is more expensive and heavier.'),
  ('Rose pasta with minced pork', 3, 'Comfort pasta with minced pork, tomato paste, cream, and parmesan.', 'Comfort pasta. Broccoli works well here for nutrition and texture.'),
  ('Beans, kale, potatoes, and dal', 3, 'Flexible legume, greens, potato, and dal meal served with rice.', 'This category includes dal, beans, chickpeas, rajma-style meals, and similar legume meals. Treat as one flexible dish family.'),
  ('Thai red curry', 3, 'Coconut-based Thai red curry with chicken, rice, and vegetables.', 'Should be rich, coconut-based, aromatic, and only moderately spicy.'),
  ('Pad Thai', 2, 'Tangy sweet-savoury noodle dish with shrimp, egg, lime, and peanuts.', 'Tangy, sweet-savoury noodle dish. Best cooked fresh rather than held for many days, but planner treats it as two servings.'),
  ('Kimchi jjigae', 2, 'Korean spicy-sour stew with kimchi, pork, tofu, and stock.', 'Korean spicy-sour stew. Heat level should be adjustable.'),
  ('Miso soup', 1, 'Quick miso soup with dashi, tofu, spring onion, and seaweed.', 'Quick one-serving soup. Miso should not be pressure cooked or boiled aggressively.')
on conflict (name) do update set
  servings = excluded.servings,
  description = excluded.description,
  notes = excluded.notes,
  updated_at = now();

insert into public.ingredients (name, category) values
  ('Rice', 'carbs'),
  ('Basmati rice', 'carbs'),
  ('Wheat noodles', 'carbs'),
  ('Rice noodles', 'carbs'),
  ('Pasta', 'carbs'),
  ('Bread', 'carbs'),
  ('Oats', 'carbs'),
  ('Potatoes', 'carbs'),
  ('Chicken', 'protein'),
  ('Minced pork', 'protein'),
  ('Pork bones', 'protein'),
  ('Paneer', 'protein'),
  ('Tofu', 'protein'),
  ('Shrimp', 'protein'),
  ('Fish cake', 'protein'),
  ('Eggs', 'protein'),
  ('Beans', 'protein'),
  ('Dal', 'protein'),
  ('Onion', 'vegetables'),
  ('Garlic', 'vegetables'),
  ('Ginger', 'vegetables'),
  ('Tomato', 'vegetables'),
  ('Banana', 'vegetables'),
  ('Kale', 'vegetables'),
  ('Bok choy', 'vegetables'),
  ('Mushrooms', 'vegetables'),
  ('Carrots', 'vegetables'),
  ('Broccoli', 'vegetables'),
  ('Spring onion', 'vegetables'),
  ('Bean sprouts', 'vegetables'),
  ('Coriander', 'vegetables'),
  ('Mint', 'vegetables'),
  ('Lime', 'vegetables'),
  ('Green Chilli', 'vegetables'),
  ('Greek yogurt', 'dairy'),
  ('Milk', 'dairy'),
  ('Parmesan cheese', 'dairy'),
  ('Cream', 'dairy'),
  ('Soy sauce', 'sauce'),
  ('Sesame oil', 'sauce'),
  ('MSG', 'pantry'),
  ('Miso', 'sauce'),
  ('Dashi or Hondashi', 'pantry'),
  ('Fish sauce', 'sauce'),
  ('Gochujang', 'sauce'),
  ('Kimchi', 'pantry'),
  ('Thai red curry paste', 'sauce'),
  ('Tamarind paste', 'sauce'),
  ('Peanut butter', 'pantry'),
  ('Biryani masala', 'spices'),
  ('Nepali-style curry spices', 'spices'),
  ('Cumin Seeds', 'spices'),
  ('Salt', 'pantry'),
  ('Oil', 'pantry'),
  ('Chilli oil', 'optional'),
  ('Black pepper', 'optional'),
  ('Peanuts', 'optional'),
  ('Coconut milk', 'pantry'),
  ('Seaweed', 'pantry'),
  ('Tomato paste', 'pantry'),
  ('Fried onions', 'optional'),
  ('Boiled eggs', 'optional'),
  ('Baked chicken', 'optional'),
  ('Baked pork', 'optional'),
  ('Chilli flakes', 'optional'),
  ('Turmeric', 'optional'),
  ('Chicken stock', 'pantry'),
  ('Ghee', 'pantry')
on conflict (name) do update set
  category = excluded.category,
  updated_at = now();

with pairs (dish_name, ingredient_name, optional) as (
  values
    ('Oats bowl', 'Oats', false),
    ('Oats bowl', 'Banana', false),
    ('Oats bowl', 'Greek yogurt', false),
    ('Oats bowl', 'Peanut butter', false),
    ('Oats bowl', 'Milk', true),
    ('Peanut butter bread with milk', 'Bread', false),
    ('Peanut butter bread with milk', 'Peanut butter', false),
    ('Peanut butter bread with milk', 'Milk', false),
    ('Chicken curry', 'Chicken', false),
    ('Chicken curry', 'Rice', false),
    ('Chicken curry', 'Onion', false),
    ('Chicken curry', 'Garlic', false),
    ('Chicken curry', 'Ginger', false),
    ('Chicken curry', 'Tomato', false),
    ('Chicken curry', 'Greek yogurt', false),
    ('Chicken curry', 'Nepali-style curry spices', false),
    ('Chicken curry', 'Salt', false),
    ('Chicken curry', 'Oil', false),
    ('Chicken curry', 'Carrots', true),
    ('Chicken curry', 'Potatoes', true),
    ('Chicken curry', 'Coriander', true),
    ('Chicken curry', 'Lime', true),
    ('Chicken biryani', 'Chicken', false),
    ('Chicken biryani', 'Basmati rice', false),
    ('Chicken biryani', 'Onion', false),
    ('Chicken biryani', 'Garlic', false),
    ('Chicken biryani', 'Ginger', false),
    ('Chicken biryani', 'Greek yogurt', false),
    ('Chicken biryani', 'Tomato', false),
    ('Chicken biryani', 'Biryani masala', false),
    ('Chicken biryani', 'Coriander', false),
    ('Chicken biryani', 'Mint', false),
    ('Chicken biryani', 'Lime', false),
    ('Chicken biryani', 'Salt', false),
    ('Chicken biryani', 'Oil', false),
    ('Chicken biryani', 'Ghee', true),
    ('Chicken biryani', 'Fried onions', true),
    ('Chicken biryani', 'Potatoes', true),
    ('Chicken biryani', 'Boiled eggs', true),
    ('Paneer Mushroom Broccoli Rice', 'Paneer', false),
    ('Paneer Mushroom Broccoli Rice', 'Mushrooms', false),
    ('Paneer Mushroom Broccoli Rice', 'Broccoli', false),
    ('Paneer Mushroom Broccoli Rice', 'Rice', false),
    ('Paneer Mushroom Broccoli Rice', 'Onion', false),
    ('Paneer Mushroom Broccoli Rice', 'Garlic', false),
    ('Paneer Mushroom Broccoli Rice', 'Soy sauce', false),
    ('Paneer Mushroom Broccoli Rice', 'Spring onion', false),
    ('Paneer Mushroom Broccoli Rice', 'Oil', false),
    ('Paneer Mushroom Broccoli Rice', 'Carrots', true),
    ('Paneer Mushroom Broccoli Rice', 'Sesame oil', true),
    ('Jeera Aloo', 'Potatoes', false),
    ('Jeera Aloo', 'Cumin Seeds', false),
    ('Jeera Aloo', 'Onion', false),
    ('Jeera Aloo', 'Garlic', false),
    ('Jeera Aloo', 'Ginger', false),
    ('Jeera Aloo', 'Coriander', false),
    ('Jeera Aloo', 'Salt', false),
    ('Jeera Aloo', 'Oil', false),
    ('Jeera Aloo', 'Green Chilli', true),
    ('Jeera Aloo', 'Lime', true),
    ('Malatang-style ramen', 'Chicken stock', false),
    ('Malatang-style ramen', 'Wheat noodles', false),
    ('Malatang-style ramen', 'Tofu', false),
    ('Malatang-style ramen', 'Fish cake', false),
    ('Malatang-style ramen', 'Shrimp', false),
    ('Malatang-style ramen', 'Bok choy', false),
    ('Malatang-style ramen', 'Mushrooms', false),
    ('Malatang-style ramen', 'Dashi or Hondashi', false),
    ('Malatang-style ramen', 'Miso', false),
    ('Malatang-style ramen', 'Soy sauce', false),
    ('Malatang-style ramen', 'Sesame oil', false),
    ('Malatang-style ramen', 'MSG', false),
    ('Malatang-style ramen', 'Garlic', false),
    ('Malatang-style ramen', 'Ginger', false),
    ('Malatang-style ramen', 'Baked chicken', true),
    ('Malatang-style ramen', 'Baked pork', true),
    ('Malatang-style ramen', 'Chilli oil', true),
    ('Malatang-style ramen', 'Spring onion', true),
    ('Tonkotsu ramen', 'Pork bones', false),
    ('Tonkotsu ramen', 'Wheat noodles', false),
    ('Tonkotsu ramen', 'Bok choy', false),
    ('Tonkotsu ramen', 'Mushrooms', false),
    ('Tonkotsu ramen', 'Spring onion', false),
    ('Tonkotsu ramen', 'Soy sauce', false),
    ('Tonkotsu ramen', 'Garlic', false),
    ('Tonkotsu ramen', 'Dashi or Hondashi', false),
    ('Tonkotsu ramen', 'Eggs', false),
    ('Tonkotsu ramen', 'Miso', true),
    ('Tonkotsu ramen', 'Sesame oil', true),
    ('Tonkotsu ramen', 'Baked pork', true),
    ('Tonkotsu ramen', 'Chilli oil', true),
    ('Rose pasta with minced pork', 'Pasta', false),
    ('Rose pasta with minced pork', 'Minced pork', false),
    ('Rose pasta with minced pork', 'Parmesan cheese', false),
    ('Rose pasta with minced pork', 'Tomato paste', false),
    ('Rose pasta with minced pork', 'Cream', false),
    ('Rose pasta with minced pork', 'Onion', false),
    ('Rose pasta with minced pork', 'Garlic', false),
    ('Rose pasta with minced pork', 'Salt', false),
    ('Rose pasta with minced pork', 'Black pepper', false),
    ('Rose pasta with minced pork', 'Broccoli', true),
    ('Rose pasta with minced pork', 'Chilli flakes', true),
    ('Rose pasta with minced pork', 'Mushrooms', true),
    ('Beans, kale, potatoes, and dal', 'Beans', false),
    ('Beans, kale, potatoes, and dal', 'Dal', false),
    ('Beans, kale, potatoes, and dal', 'Kale', false),
    ('Beans, kale, potatoes, and dal', 'Potatoes', false),
    ('Beans, kale, potatoes, and dal', 'Onion', false),
    ('Beans, kale, potatoes, and dal', 'Garlic', false),
    ('Beans, kale, potatoes, and dal', 'Ginger', false),
    ('Beans, kale, potatoes, and dal', 'Rice', false),
    ('Beans, kale, potatoes, and dal', 'Salt', false),
    ('Beans, kale, potatoes, and dal', 'Oil', false),
    ('Beans, kale, potatoes, and dal', 'Tomato', true),
    ('Beans, kale, potatoes, and dal', 'Cumin Seeds', true),
    ('Beans, kale, potatoes, and dal', 'Turmeric', true),
    ('Beans, kale, potatoes, and dal', 'Coriander', true),
    ('Thai red curry', 'Chicken', false),
    ('Thai red curry', 'Rice', false),
    ('Thai red curry', 'Coconut milk', false),
    ('Thai red curry', 'Thai red curry paste', false),
    ('Thai red curry', 'Fish sauce', false),
    ('Thai red curry', 'Lime', false),
    ('Thai red curry', 'Carrots', false),
    ('Thai red curry', 'Broccoli', false),
    ('Thai red curry', 'Onion', false),
    ('Thai red curry', 'Mushrooms', true),
    ('Thai red curry', 'Bok choy', true),
    ('Thai red curry', 'Tofu', true),
    ('Thai red curry', 'Shrimp', true),
    ('Pad Thai', 'Rice noodles', false),
    ('Pad Thai', 'Shrimp', false),
    ('Pad Thai', 'Eggs', false),
    ('Pad Thai', 'Bean sprouts', false),
    ('Pad Thai', 'Spring onion', false),
    ('Pad Thai', 'Tamarind paste', false),
    ('Pad Thai', 'Fish sauce', false),
    ('Pad Thai', 'Lime', false),
    ('Pad Thai', 'Peanuts', false),
    ('Pad Thai', 'Tofu', true),
    ('Pad Thai', 'Chicken', true),
    ('Pad Thai', 'Chilli flakes', true),
    ('Kimchi jjigae', 'Kimchi', false),
    ('Kimchi jjigae', 'Minced pork', false),
    ('Kimchi jjigae', 'Tofu', false),
    ('Kimchi jjigae', 'Onion', false),
    ('Kimchi jjigae', 'Garlic', false),
    ('Kimchi jjigae', 'Gochujang', false),
    ('Kimchi jjigae', 'Chicken stock', false),
    ('Kimchi jjigae', 'Spring onion', false),
    ('Kimchi jjigae', 'Mushrooms', true),
    ('Kimchi jjigae', 'Eggs', true),
    ('Kimchi jjigae', 'Sesame oil', true),
    ('Miso soup', 'Miso', false),
    ('Miso soup', 'Dashi or Hondashi', false),
    ('Miso soup', 'Tofu', false),
    ('Miso soup', 'Spring onion', false),
    ('Miso soup', 'Seaweed', false),
    ('Miso soup', 'Mushrooms', true),
    ('Miso soup', 'Bok choy', true)
)
insert into public.dish_ingredients (dish_id, ingredient_id, optional)
select d.id, i.id, pairs.optional
from pairs
join public.dishes d on d.name = pairs.dish_name
join public.ingredients i on i.name = pairs.ingredient_name
on conflict (dish_id, ingredient_id) do update set
  optional = excluded.optional;

with steps (dish_name, step_number, instruction) as (
  values
    ('Oats bowl', 1, 'Add oats to a bowl.'),
    ('Oats bowl', 2, 'Add Greek yogurt.'),
    ('Oats bowl', 3, 'Slice banana on top.'),
    ('Oats bowl', 4, 'Add peanut butter.'),
    ('Oats bowl', 5, 'Add a splash of milk if a looser texture is preferred.'),
    ('Oats bowl', 6, 'Mix and eat immediately, or chill for overnight oats.'),
    ('Peanut butter bread with milk', 1, 'Toast or warm bread if preferred.'),
    ('Peanut butter bread with milk', 2, 'Spread peanut butter.'),
    ('Peanut butter bread with milk', 3, 'Serve with milk.'),
    ('Peanut butter bread with milk', 4, 'Optionally dip bread into milk.'),
    ('Chicken curry', 1, 'Marinate chicken with yogurt, salt, ginger, garlic, and curry spices.'),
    ('Chicken curry', 2, 'Fry onion until softened or lightly browned.'),
    ('Chicken curry', 3, 'Add garlic and ginger.'),
    ('Chicken curry', 4, 'Add tomato and cook until thickened.'),
    ('Chicken curry', 5, 'Add chicken and cook until sealed.'),
    ('Chicken curry', 6, 'Add water as needed and simmer until chicken is cooked.'),
    ('Chicken curry', 7, 'Adjust salt and spice level.'),
    ('Chicken curry', 8, 'Serve with rice.'),
    ('Chicken biryani', 1, 'Marinate chicken with yogurt, ginger, garlic, biryani masala, salt, and lime.'),
    ('Chicken biryani', 2, 'Parboil basmati rice until partly cooked.'),
    ('Chicken biryani', 3, 'Fry onions until golden.'),
    ('Chicken biryani', 4, 'Cook marinated chicken with tomato until mostly cooked.'),
    ('Chicken biryani', 5, 'Layer rice, chicken, coriander, mint, and optional fried onions.'),
    ('Chicken biryani', 6, 'Steam on low heat until rice is fully cooked.'),
    ('Chicken biryani', 7, 'Rest before serving.'),
    ('Paneer Mushroom Broccoli Rice', 1, 'Cook rice separately.'),
    ('Paneer Mushroom Broccoli Rice', 2, 'Pan-fry paneer until lightly golden.'),
    ('Paneer Mushroom Broccoli Rice', 3, 'Cook onion, garlic, mushrooms, and broccoli.'),
    ('Paneer Mushroom Broccoli Rice', 4, 'Add cooked rice.'),
    ('Paneer Mushroom Broccoli Rice', 5, 'Add soy sauce and mix.'),
    ('Paneer Mushroom Broccoli Rice', 6, 'Add paneer back in.'),
    ('Paneer Mushroom Broccoli Rice', 7, 'Finish with spring onion.'),
    ('Jeera Aloo', 1, 'Boil or parboil potatoes until just tender.'),
    ('Jeera Aloo', 2, 'Cut potatoes into bite-sized pieces.'),
    ('Jeera Aloo', 3, 'Heat oil and toast cumin seeds until fragrant.'),
    ('Jeera Aloo', 4, 'Add onion and cook until softened.'),
    ('Jeera Aloo', 5, 'Add garlic, ginger, and optional green chilli.'),
    ('Jeera Aloo', 6, 'Add potatoes and salt.'),
    ('Jeera Aloo', 7, 'Pan-fry until the potatoes are lightly crisp at the edges.'),
    ('Jeera Aloo', 8, 'Finish with coriander and optional lime.'),
    ('Malatang-style ramen', 1, 'Heat chicken stock.'),
    ('Malatang-style ramen', 2, 'Add garlic, ginger, dashi, soy sauce, MSG, and miso.'),
    ('Malatang-style ramen', 3, 'Add mushrooms, fish cake, tofu, and shrimp.'),
    ('Malatang-style ramen', 4, 'Add noodles.'),
    ('Malatang-style ramen', 5, 'Add bok choy near the end.'),
    ('Malatang-style ramen', 6, 'Finish with sesame oil and optional chilli oil.'),
    ('Malatang-style ramen', 7, 'Top with baked chicken or pork if available.'),
    ('Tonkotsu ramen', 1, 'Blanch pork bones, then discard blanching water.'),
    ('Tonkotsu ramen', 2, 'Rinse bones.'),
    ('Tonkotsu ramen', 3, 'Pressure cook bones with clean water until broth is rich.'),
    ('Tonkotsu ramen', 4, 'Strain broth.'),
    ('Tonkotsu ramen', 5, 'Season broth with soy sauce, garlic, dashi, and optional miso.'),
    ('Tonkotsu ramen', 6, 'Cook noodles separately.'),
    ('Tonkotsu ramen', 7, 'Add noodles to bowl.'),
    ('Tonkotsu ramen', 8, 'Add broth.'),
    ('Tonkotsu ramen', 9, 'Top with egg, bok choy, mushrooms, spring onion, and pork if available.'),
    ('Rose pasta with minced pork', 1, 'Boil pasta until al dente.'),
    ('Rose pasta with minced pork', 2, 'Fry onion and garlic.'),
    ('Rose pasta with minced pork', 3, 'Add minced pork and cook through.'),
    ('Rose pasta with minced pork', 4, 'Add tomato paste and cook until deeper red.'),
    ('Rose pasta with minced pork', 5, 'Add cream.'),
    ('Rose pasta with minced pork', 6, 'Add pasta water to loosen the sauce.'),
    ('Rose pasta with minced pork', 7, 'Mix pasta into sauce.'),
    ('Rose pasta with minced pork', 8, 'Finish with parmesan cheese.'),
    ('Beans, kale, potatoes, and dal', 1, 'Soak beans if using dried beans.'),
    ('Beans, kale, potatoes, and dal', 2, 'Cook beans and dal until soft.'),
    ('Beans, kale, potatoes, and dal', 3, 'Cook potatoes separately or in the same pot.'),
    ('Beans, kale, potatoes, and dal', 4, 'Fry onion, garlic, and ginger.'),
    ('Beans, kale, potatoes, and dal', 5, 'Add spices if using.'),
    ('Beans, kale, potatoes, and dal', 6, 'Combine beans, dal, potatoes, and kale.'),
    ('Beans, kale, potatoes, and dal', 7, 'Simmer until thick and cohesive.'),
    ('Beans, kale, potatoes, and dal', 8, 'Serve with rice.'),
    ('Thai red curry', 1, 'Fry red curry paste in oil.'),
    ('Thai red curry', 2, 'Add chicken and coat in paste.'),
    ('Thai red curry', 3, 'Add coconut milk.'),
    ('Thai red curry', 4, 'Add carrots and other firm vegetables.'),
    ('Thai red curry', 5, 'Simmer until chicken is cooked.'),
    ('Thai red curry', 6, 'Add broccoli near the end.'),
    ('Thai red curry', 7, 'Season with fish sauce and lime.'),
    ('Thai red curry', 8, 'Serve with rice.'),
    ('Pad Thai', 1, 'Soak rice noodles until flexible.'),
    ('Pad Thai', 2, 'Mix sauce using tamarind, fish sauce, and a little sugar if needed.'),
    ('Pad Thai', 3, 'Cook shrimp or chosen protein.'),
    ('Pad Thai', 4, 'Push protein aside and scramble egg.'),
    ('Pad Thai', 5, 'Add noodles and sauce.'),
    ('Pad Thai', 6, 'Toss until noodles absorb sauce.'),
    ('Pad Thai', 7, 'Add bean sprouts and spring onion.'),
    ('Pad Thai', 8, 'Finish with lime and peanuts.'),
    ('Kimchi jjigae', 1, 'Fry pork until browned.'),
    ('Kimchi jjigae', 2, 'Add onion and garlic.'),
    ('Kimchi jjigae', 3, 'Add kimchi and cook until softened.'),
    ('Kimchi jjigae', 4, 'Add gochujang.'),
    ('Kimchi jjigae', 5, 'Add chicken stock.'),
    ('Kimchi jjigae', 6, 'Simmer until broth is rich and sour-spicy.'),
    ('Kimchi jjigae', 7, 'Add tofu near the end.'),
    ('Kimchi jjigae', 8, 'Finish with spring onion.'),
    ('Miso soup', 1, 'Heat water or light stock.'),
    ('Miso soup', 2, 'Add dashi.'),
    ('Miso soup', 3, 'Add tofu and seaweed.'),
    ('Miso soup', 4, 'Turn heat low.'),
    ('Miso soup', 5, 'Dissolve miso into the soup without boiling hard.'),
    ('Miso soup', 6, 'Finish with spring onion.')
)
insert into public.recipe_steps (dish_id, step_number, instruction)
select d.id, steps.step_number, steps.instruction
from steps
join public.dishes d on d.name = steps.dish_name
on conflict (dish_id, step_number) do update set
  instruction = excluded.instruction;
